### 데이터 불러오기

In [ ]:
import os
import xml.etree.ElementTree as ET
import pandas as pd

In [ ]:
xml_dir = '/Users/Jinmi/Downloads/도로주행영상/Training/bb/도심로'

# xml 경로들 모으기
xml_list = []
for (dirpath, dirnames, filenames) in os.walk(xml_dir):
    for file in filenames:
        combined_path = os.path.join(dirpath, file)
        if '.DS_Store' in combined_path:
            continue
        else:
            xml_list += [combined_path]

In [ ]:
# 총 라벨 xml 개수
len(xml_list)

71030

In [ ]:
# 샘플로 확인해보기
xml_list[:5]

['/Users/Jinmi/Downloads/도로주행영상/Training/bb/도심로/야간일몰/맑음/60_전방/20200708_200952/2_annotations_v001_1/2_20200708_200952_000420_v001_1.xml',
 '/Users/Jinmi/Downloads/도로주행영상/Training/bb/도심로/야간일몰/맑음/60_전방/20200708_200952/2_annotations_v001_1/2_20200708_200952_003690_v001_1.xml',
 '/Users/Jinmi/Downloads/도로주행영상/Training/bb/도심로/야간일몰/맑음/60_전방/20200708_200952/2_annotations_v001_1/2_20200708_200952_003750_v001_1.xml',
 '/Users/Jinmi/Downloads/도로주행영상/Training/bb/도심로/야간일몰/맑음/60_전방/20200708_200952/2_annotations_v001_1/2_20200708_200952_000000_v001_1.xml',
 '/Users/Jinmi/Downloads/도로주행영상/Training/bb/도심로/야간일몰/맑음/60_전방/20200708_200952/2_annotations_v001_1/2_20200708_200952_000150_v001_1.xml']

### 필요한 데이터 추출 연습

In [ ]:
# 클래스명 리스트 선언
names = ['none_of_the_above',
         'Vehicle_Car',
         'Vehicle_Bus',
         'Vehicle_Motorcycle',
         'Vehicle_Unknown',
         'Pedestrian_Pedestrian',
         'Pedestrian_Bicycle',
         'Lane_White_Dash',
         'Lane_White_Solid',
         'Lane_Yellow_Dash',
         'Lane_Yellow_Solid',
         'Lane_Blue_Dash',
         'Lane_Blue_Solid',
         'TrafficLight_Red',
         'TrafficLight_Yellow',
         'TrafficLight_Green',
         'TrafficLight_Arrow',
         'TrafficLight_RedArrow',
         'TrafficLight_YellowArrow',
         'TrafficLight_GreenArrow',
         'TrafficSign_Speed',
         'TrafficSign_Else',
         'RoadMark_StopLine',
         'RoadMark_Crosswalk',
         'RoadMark_Number',
         'RoadMark_Character',
         'RoadMarkArrow_Straight',
         'RoadMarkArrow_Left',
         'RoadMarkArrow_Right',
         'RoadMarkArrow_StraightLeft',
         'RoadMarkArrow_StraightRight',
         'RoadMarkArrow_Uturn',
         'RoadMarkArrow_Else',
         'FreeSpace'
        ]

# 클래스명마다 고유 int 부여
names_dict = {'none_of_the_above' : 0,
              'Vehicle_Car' : 1,
              'Vehicle_Bus' : 2,
              'Vehicle_Motorcycle' : 3,
              'Vehicle_Unknown' : 4,
              'Pedestrian_Pedestrian' : 5,
              'Pedestrian_Bicycle' : 6,
              'Lane_White_Dash' : 7,
              'Lane_White_Solid' : 8,
              'Lane_Yellow_Dash' : 9,
              'Lane_Yellow_Solid' : 10,
              'Lane_Blue_Dash' : 11,
              'Lane_Blue_Solid' : 12,
              'TrafficLight_Red' : 13,
              'TrafficLight_Yellow' : 14,
              'TrafficLight_Green' : 15,
              'TrafficLight_Arrow' : 16,
              'TrafficLight_RedArrow' : 17,
              'TrafficLight_YellowArrow' : 18,
              'TrafficLight_GreenArrow' : 19,
              'TrafficSign_Speed' : 20,
              'TrafficSign_Else' : 21,
              'RoadMark_StopLine' : 22,
              'RoadMark_Crosswalk' : 23,
              'RoadMark_Number' : 24,
              'RoadMark_Character' : 25,
              'RoadMarkArrow_Straight' : 26,
              'RoadMarkArrow_Left' : 27,
              'RoadMarkArrow_Right' : 28,
              'RoadMarkArrow_StraightLeft' : 29,
              'RoadMarkArrow_StraightRight' : 30,
              'RoadMarkArrow_Uturn' : 31,
              'RoadMarkArrow_Else' : 32,
              'FreeSpace' : 33,
        }

# 데이터프레임에서 컬럼 이름
columns = ['<=0.0001', '<=0.001', '<=0.01', '<=0.1', '0.1<']

In [ ]:
# 계수한 거 기록할 베이스 표 만들기

table = [[0 for _ in range(5)] for _ in range(len(names))]
table

[[0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0]]

In [ ]:
def name2num(name):
    names_dict = {'none_of_the_above' : 0,
              'Vehicle_Car' : 1,
              'Vehicle_Bus' : 2,
              'Vehicle_Motorcycle' : 3,
              'Vehicle_Unknown' : 4,
              'Pedestrian_Pedestrian' : 5,
              'Pedestrian_Bicycle' : 6,
              'Lane_White_Dash' : 7,
              'Lane_White_Solid' : 8,
              'Lane_Yellow_Dash' : 9,
              'Lane_Yellow_Solid' : 10,
              'Lane_Blue_Dash' : 11,
              'Lane_Blue_Solid' : 12,
              'TrafficLight_Red' : 13,
              'TrafficLight_Yellow' : 14,
              'TrafficLight_Green' : 15,
              'TrafficLight_Arrow' : 16,
              'TrafficLight_RedArrow' : 17,
              'TrafficLight_YellowArrow' : 18,
              'TrafficLight_GreenArrow' : 19,
              'TrafficSign_Speed' : 20,
              'TrafficSign_Else' : 21,
              'RoadMark_StopLine' : 22,
              'RoadMark_Crosswalk' : 23,
              'RoadMark_Number' : 24,
              'RoadMark_Character' : 25,
              'RoadMarkArrow_Straight' : 26,
              'RoadMarkArrow_Left' : 27,
              'RoadMarkArrow_Right' : 28,
              'RoadMarkArrow_StraightLeft' : 29,
              'RoadMarkArrow_StraightRight' : 30,
              'RoadMarkArrow_Uturn' : 31,
              'RoadMarkArrow_Else' : 32,
              'FreeSpace' : 33,
        }
    return names_dict[name]

#### 샘플로 추출해보기

In [ ]:
xml_path = xml_list[1]
print(xml_path)
tree = ET.parse(xml_path)
root = tree.getroot()

/Users/Jinmi/Downloads/도로주행영상/Training/bb/도심로/야간일몰/맑음/60_전방/20200708_200952/2_annotations_v001_1/2_20200708_200952_003690_v001_1.xml

In [ ]:
img_width = int(root.find('size').find('width').text)
img_height = int(root.find('size').find('height').text)

for ob in root.findall('object'):
    bbox = ob.find('bndbox')
    name = ob.find('name').text
    xmin = int(bbox.find('xmin').text) / img_width
    ymin = int(bbox.find('ymin').text) / img_height
    xmax = int(bbox.find('xmax').text) / img_width
    ymax = int(bbox.find('ymax').text) / img_height
    
    width = xmax - xmin 
    height = ymax - ymin
    area = width * height
    if area > 0 and area <= 0.0001:
        col_idx = 0
    elif area > 0.0001 and area <= 0.001:
        col_idx = 1
    elif area > 0.001 and area <= 0.01:
        col_idx = 2
    elif area > 0.01 and area <= 0.1:
        col_idx = 3
    elif area > 0.1:
        col_idx = 4
    row_idx = int(name2num(name))
    
    table[row_idx][col_idx] += 1

In [ ]:
table

[[0, 0, 0, 0, 0],
 [0, 1, 1, 2, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [2, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0]]

In [ ]:
pd.DataFrame(table, index=names, columns=columns)

                             <=0.0001  <=0.001  <=0.01  <=0.1  0.1<
none_of_the_above                   0        0       0      0     0
Vehicle_Car                         0        1       1      2     0
Vehicle_Bus                         0        0       0      0     0
Vehicle_Motorcycle                  0        0       0      0     0
Vehicle_Unknown                     0        0       0      1     0
Pedestrian_Pedestrian               0        0       0      0     0
Pedestrian_Bicycle                  0        0       0      0     0
Lane_White_Dash                     0        0       0      0     0
Lane_White_Solid                    0        0       0      0     0
Lane_Yellow_Dash                    0        0       0      0     0
Lane_Yellow_Solid                   0        0       0      0     0
Lane_Blue_Dash                      0        0       0      0     0
Lane_Blue_Solid                     0        0       0      0     0
TrafficLight_Red                    2        0       0      0     0
TrafficLight_Yellow                 0        0       0      0     0
TrafficLight_Green                  0        0       0      0     0
TrafficLight_Arrow                  0        0       0      0     0
TrafficLight_RedArrow               0        0       0      0     0
TrafficLight_YellowArrow            0        0       0      0     0
TrafficLight_GreenArrow             0        0       0      0     0
TrafficSign_Speed                   0        0       0      0     0
TrafficSign_Else                    0        0       0      0     0
RoadMark_StopLine                   0        0       1      0     0
RoadMark_Crosswalk                  0        0       0      1     0
RoadMark_Number                     0        0       0      0     0
RoadMark_Character                  0        0       0      0     0
RoadMarkArrow_Straight              0        1       0      0     0
RoadMarkArrow_Left                  0        0       0      0     0
RoadMarkArrow_Right                 0        0       0      0     0
RoadMarkArrow_StraightLeft          0        1       0      0     0
RoadMarkArrow_StraightRight         0        0       0      0     0
RoadMarkArrow_Uturn                 0        0       0      0     0
RoadMarkArrow_Else                  0        1       0      0     0
FreeSpace                           0        0       0      0     0

### 전체 라벨에 대해서 진행

In [ ]:
# 클래스명 리스트 선언
names = ['none_of_the_above',
         'Vehicle_Car',
         'Vehicle_Bus',
         'Vehicle_Motorcycle',
         'Vehicle_Unknown',
         'Pedestrian_Pedestrian',
         'Pedestrian_Bicycle',
         'Lane_White_Dash',
         'Lane_White_Solid',
         'Lane_Yellow_Dash',
         'Lane_Yellow_Solid',
         'Lane_Blue_Dash',
         'Lane_Blue_Solid',
         'TrafficLight_Red',
         'TrafficLight_Yellow',
         'TrafficLight_Green',
         'TrafficLight_Arrow',
         'TrafficLight_RedArrow',
         'TrafficLight_YellowArrow',
         'TrafficLight_GreenArrow',
         'TrafficSign_Speed',
         'TrafficSign_Else',
         'RoadMark_StopLine',
         'RoadMark_Crosswalk',
         'RoadMark_Number',
         'RoadMark_Character',
         'RoadMarkArrow_Straight',
         'RoadMarkArrow_Left',
         'RoadMarkArrow_Right',
         'RoadMarkArrow_StraightLeft',
         'RoadMarkArrow_StraightRight',
         'RoadMarkArrow_Uturn',
         'RoadMarkArrow_Else',
         'FreeSpace'
        ]

names_dict = {'none_of_the_above' : 0,
              'Vehicle_Car' : 1,
              'Vehicle_Bus' : 2,
              'Vehicle_Motorcycle' : 3,
              'Vehicle_Unknown' : 4,
              'Pedestrian_Pedestrian' : 5,
              'Pedestrian_Bicycle' : 6,
              'Lane_White_Dash' : 7,
              'Lane_White_Solid' : 8,
              'Lane_Yellow_Dash' : 9,
              'Lane_Yellow_Solid' : 10,
              'Lane_Blue_Dash' : 11,
              'Lane_Blue_Solid' : 12,
              'TrafficLight_Red' : 13,
              'TrafficLight_Yellow' : 14,
              'TrafficLight_Green' : 15,
              'TrafficLight_Arrow' : 16,
              'TrafficLight_RedArrow' : 17,
              'TrafficLight_YellowArrow' : 18,
              'TrafficLight_GreenArrow' : 19,
              'TrafficSign_Speed' : 20,
              'TrafficSign_Else' : 21,
              'RoadMark_StopLine' : 22,
              'RoadMark_Crosswalk' : 23,
              'RoadMark_Number' : 24,
              'RoadMark_Character' : 25,
              'RoadMarkArrow_Straight' : 26,
              'RoadMarkArrow_Left' : 27,
              'RoadMarkArrow_Right' : 28,
              'RoadMarkArrow_StraightLeft' : 29,
              'RoadMarkArrow_StraightRight' : 30,
              'RoadMarkArrow_Uturn' : 31,
              'RoadMarkArrow_Else' : 32,
              'FreeSpace' : 33,
        }

def name2num(name):
    names_dict = {'none_of_the_above' : 0,
              'Vehicle_Car' : 1,
              'Vehicle_Bus' : 2,
              'Vehicle_Motorcycle' : 3,
              'Vehicle_Unknown' : 4,
              'Pedestrian_Pedestrian' : 5,
              'Pedestrian_Bicycle' : 6,
              'Lane_White_Dash' : 7,
              'Lane_White_Solid' : 8,
              'Lane_Yellow_Dash' : 9,
              'Lane_Yellow_Solid' : 10,
              'Lane_Blue_Dash' : 11,
              'Lane_Blue_Solid' : 12,
              'TrafficLight_Red' : 13,
              'TrafficLight_Yellow' : 14,
              'TrafficLight_Green' : 15,
              'TrafficLight_Arrow' : 16,
              'TrafficLight_RedArrow' : 17,
              'TrafficLight_YellowArrow' : 18,
              'TrafficLight_GreenArrow' : 19,
              'TrafficSign_Speed' : 20,
              'TrafficSign_Else' : 21,
              'RoadMark_StopLine' : 22,
              'RoadMark_Crosswalk' : 23,
              'RoadMark_Number' : 24,
              'RoadMark_Character' : 25,
              'RoadMarkArrow_Straight' : 26,
              'RoadMarkArrow_Left' : 27,
              'RoadMarkArrow_Right' : 28,
              'RoadMarkArrow_StraightLeft' : 29,
              'RoadMarkArrow_StraightRight' : 30,
              'RoadMarkArrow_Uturn' : 31,
              'RoadMarkArrow_Else' : 32,
              'FreeSpace' : 33,
        }
    return names_dict[name]

columns = ['<=0.0001', '<=0.001', '<=0.01', '<=0.1', '0.1<']

In [ ]:
%%time
import os
import xml.etree.ElementTree as ET
import pandas as pd

xml_dir = '/Users/Jinmi/Downloads/도로주행영상/Training/bb/도심로'

# xml 경로들 모으기
xml_list = []
for (dirpath, dirnames, filenames) in os.walk(xml_dir):
    for file in filenames:
        combined_path = os.path.join(dirpath, file)
        if '.DS_Store' in combined_path:
            continue
        else:
            xml_list += [combined_path]

# 베이스 표 만들기
table = [[0 for _ in range(5)] for _ in range(len(names))]
table

for xml_path in xml_list:
    # XML parsing
    tree = ET.parse(xml_path)
    root = tree.getroot()

    # 이미지 넓이, 높이 구하기
    img_width = int(root.find('size').find('width').text)
    img_height = int(root.find('size').find('height').text)

    # 객체들 정보 추출
    for ob in root.findall('object'):
        bbox = ob.find('bndbox') # bounding box
        name = ob.find('name').text # class
        xmin = int(bbox.find('xmin').text) / img_width  # normalise
        ymin = int(bbox.find('ymin').text) / img_height # normalise
        xmax = int(bbox.find('xmax').text) / img_width  # normalise
        ymax = int(bbox.find('ymax').text) / img_height # normalise

        # 객체의 면적 구하기
        width = xmax - xmin 
        height = ymax - ymin
        area = width * height

        # 객체의 면적에 따른 테이블에서의 column index 할당
        if area > 0 and area <= 0.0001:
            col_idx = 0
        elif area > 0.0001 and area <= 0.001:
            col_idx = 1
        elif area > 0.001 and area <= 0.01:
            col_idx = 2
        elif area > 0.01 and area <= 0.1:
            col_idx = 3
        elif area > 0.1:
            col_idx = 4

        # 객체 이름에 따른 테이블에서의 row index 할당
        row_idx = int(name2num(name))

        # 더하기
        table[row_idx][col_idx] += 1

CPU times: user 19.4 s, sys: 8.76 s, total: 28.2 s
Wall time: 46.4 s

#### 원본 데이터프레임 생성 및 확인

In [ ]:
df = pd.DataFrame(table, index=names, columns=columns)

In [ ]:
df

                             <=0.0001  <=0.001  <=0.01  <=0.1  0.1<
none_of_the_above                   0        0       0      0     0
Vehicle_Car                         3    86658  198685  71174  6289
Vehicle_Bus                         1     7415   16611   7362  1591
Vehicle_Motorcycle                  0     2537    4381    728    31
Vehicle_Unknown                     1    19030   57414  24051  4129
Pedestrian_Pedestrian             709    36615   18188   1605    37
Pedestrian_Bicycle                  0     1510    2598    275     2
Lane_White_Dash                     0        0       0      0     0
Lane_White_Solid                    0        0       0      0     0
Lane_Yellow_Dash                    0        0       0      0     0
Lane_Yellow_Solid                   0        0       0      0     0
Lane_Blue_Dash                      0        0       0      0     0
Lane_Blue_Solid                     0        0       0      0     0
TrafficLight_Red                 6276    11514    2864      2     0
TrafficLight_Yellow               647     1049     265      0     0
TrafficLight_Green              10286    14325    3586      3     0
TrafficLight_Arrow                 55       98      36      0     0
TrafficLight_RedArrow             742     1526     311      0     0
TrafficLight_YellowArrow            2       19       0      0     0
TrafficLight_GreenArrow          1131     2310     572      0     0
TrafficSign_Speed                   3     5508    2981     21     0
TrafficSign_Else                   23    18629   13888    327     2
RoadMark_StopLine                 488     6439    9592   3055    78
RoadMark_Crosswalk                  0      176    5382   8969  3370
RoadMark_Number                   182     2702    2288    559     0
RoadMark_Character                276     8274    9388   2744    15
RoadMarkArrow_Straight            153     6213    6109   1437     1
RoadMarkArrow_Left                 14     1466    1686    517     0
RoadMarkArrow_Right                10     1021    1053    246     0
RoadMarkArrow_StraightLeft          1      433     548    193     0
RoadMarkArrow_StraightRight         0      676     792    173     0
RoadMarkArrow_Uturn                 0      421     537    197     0
RoadMarkArrow_Else                117     8004    8155   1996    12
FreeSpace                           0        0       0      0     0

#### KITTI 라벨에 맞춘 데이터프레임 생성

In [ ]:
df_for_kitti = pd.DataFrame(data=0, index=['Car', 'Tram', 'Pedestrian', 'Cyclist', 'Etc'], columns=columns)
df_for_kitti

            <=0.0001  <=0.001  <=0.01  <=0.1  0.1<
Car                0        0       0      0     0
Tram               0        0       0      0     0
Pedestrian         0        0       0      0     0
Cyclist            0        0       0      0     0
Etc                0        0       0      0     0

In [ ]:
for idx in df.index:
    if idx == 'Vehicle_Car':
        df_for_kitti.loc['Car'] += df.loc[idx]
    elif idx == 'Vehicle_Unknown':
        df_for_kitti.loc['Car'] += df.loc[idx]
    elif idx == 'Vehicle_Bus':
        df_for_kitti.loc['Tram'] += df.loc[idx]
    elif idx == 'Pedestrian_Pedestrian':
        df_for_kitti.loc['Pedestrian'] += df.loc[idx]
    elif idx == 'Pedestrian_Bicycle':
        df_for_kitti.loc['Cyclist'] += df.loc[idx]
    else:
        df_for_kitti.loc['Etc'] += df.loc[idx]

In [ ]:
df_for_kitti

            <=0.0001  <=0.001  <=0.01  <=0.1   0.1<
Car                4   105688  256099  95225  10418
Tram               1     7415   16611   7362   1591
Pedestrian       709    36615   18188   1605     37
Cyclist            0     1510    2598    275      2
Etc            20406    93340   74414  21167   3509

In [ ]:
# 원본 데이터프레임 컬럼별 개수 확인
df.sum()

<=0.0001     21120
<=0.001     244568
<=0.01      367910
<=0.1       125634
0.1<         15557
dtype: int64

In [ ]:
# 새로운 데이터프레임 컬럼별 개수 확인
df_for_kitti.sum()

<=0.0001     21120
<=0.001     244568
<=0.01      367910
<=0.1       125634
0.1<         15557
dtype: int64

In [ ]:
# 새로운 데이터프레임 row별 sum 확인
df_for_kitti.sum(axis=1)

Car           467434
Tram           32980
Pedestrian     57154
Cyclist         4385
Etc           212836
dtype: int64

In [ ]:
# Etc row를 제외한 데이터들 확인
df_for_kitti.iloc[:-1, :]

            <=0.0001  <=0.001  <=0.01  <=0.1   0.1<
Car                4   105688  256099  95225  10418
Tram               1     7415   16611   7362   1591
Pedestrian       709    36615   18188   1605     37
Cyclist            0     1510    2598    275      2

In [ ]:
df_for_kitti.iloc[:-1, :].sum()

<=0.0001       714
<=0.001     151228
<=0.01      293496
<=0.1       104467
0.1<         12048
dtype: int64